### PR TITLE
Re-added PR 10 changes

### PR DESCRIPTION
**Pull request by alex-phillips**
For some reason (maybe my fault), the last PR removed the changes I made in PR 10. This adds those changes back.

### CODE REVIEW

**Comment by jonhoo** [comment]
Ah, no, I removed those parts of the fix, because they do not work correctly. In particular:

  - What if `this.duration` is not known (which can easily be the case for some videos)?
  - What if `skipOffset` is given in percent?
  - What if `point['offset']` is given in percent?
  - Converting all offsets to percent, while perhaps convenient, is not entirely faithful to what the author of the VAST intended. For example, they might want the ad to play at *exactly* 01:45 into the video to match up with a particular scene, whereas conversion to a percentage + rounding might cause that to become 01:47, causing a jarring user experience.

**Comment by alex-phillips** [comment]
So should we instead convert everything to an elapsed time value? Or is this code that we should rely the user of the library to determine? Regardless, I feel it would be highly convenient to add support for ordering the events in which they're supposed to occur which would require them to have a uniform format. That way a user can determine the 'skip' event based on fetching the 'next' event in the returned array rather than having to iterate through to find it (if it exists).

**Comment by jonhoo** [comment]
My point is that I don't think that is possible to do in practice, because you might not know `this.duration`, preventing any conversion from time to percent, or vice-versa. I agree that it would be very convenient, but it's not clear that it's possible.

One alternative would be to maintain two lists: one for percentages, and one for absolute times, and each one sorted. That way, finding the next even requires only checking two elements (one for each list).

**Comment by alex-phillips** [comment]
In that case I think it would be best then to store both values (when possible) and sort. You are currently storing a percentage value all of the time for the `quartile` events, but to your point, if the `duration` isn't always known, then these tracking points are completely unusable, correct?

I imagine that all tracking point values would be passed the same per VAST object (there wouldn't be a mix of percentage and numeric values), and if a percentage is given, then the duration (should) be present as well. We could calculate both, but actually sort based on what the passed values actually are, and return.

**Comment by jonhoo** [comment]
If the duration is never learned, then yes, all percentiles would be useless. If the VAST authors include a percentile, but not a duration, then they messed up. 

I don't think you're right that all tracking point values will be the same for a given object. It is certainly not something the library can assume. Maybe the correct way to do this would be to convert all values to absolute timecodes, and simply ignore percentiles if `this.duration` is unknown. This way, we could sort the values like you wanted (though the values would be timecodes, not percentages, but that shouldn't really be a problem).

**Comment by alex-phillips** [comment]
See changes. Added `timelapse` property (when duration is available) and sorting either by `timelapse` or `offset`. That way code already using the library and using `offset` won't be broken.

**Comment by jonhoo** [comment]
You seem to be inconsistent about which of `offset` and `timelapse` contain a percentage offset? Why are you not just always making it one field? I'm also not sure about the name `timelapse` --- what meaning are you attributing to it?

Also, the sorting code can be simplified by moving the body of the loop from line 1325 into the sorting function at 1340.

**Comment by alex-phillips** [comment]
So I was referencing 'timelapse' as the amount of seconds into the video the event needs to occur and tried to keep 'offset' the percentage for consistency with how this was done before. But the `default` statement isn't doing percentage anyway (from your code), so I think changing it all together would be best for consistency.

In that case, we should have `offset` be the number of seconds at which the event should occur have have another key, maybe `percentOffset` that is the percentage. Thoughts?

Also, fixed my code for this but wanted to run it by you before pushing commit.

**Comment by jonhoo** [comment]
Yes, that sounds reasonable.

**Comment by alex-phillips** [comment]
@jonhoo pushed changes.

**Comment by alex-phillips** [comment]
Yeah. Apparently I can't math today. Fixed.

**Comment by jonhoo** [comment]
Line 1307: `your_string.indexOf('%')`, `your_string` is not defined.

Also, the same if needs to be applied to the default case, because there too, offset could be in percent.

**Comment by alex-phillips** [comment]
Fixed.

**Pull request merged**
