### PR TITLE
Add support for recursive ad fetch failures.

### PR DESCRIPTION
**Pull request by exonintrendo**
We encountered an issue where the initial VAST request would call a redirect to another VAST URL which didn't contain any ad data. Now, if there is a failure down the line, an exception is thrown and the original user-defined callback is always executed, passing in `null` when there was a failure.

We also ran into an issue where the `finger` method would trigger XHR Cross-Origin console errors. So, if possible, we first attempt to create a new `Image` object and set the `src` equal to the tracking point URL as this will make the proper network request without throwing an XHR error.

### CODE REVIEW

**Comment by jonhoo** [comment]
Thanks! See my inline comments above.
I'd also prefer it if you split this into multiple PRs, one for each modification. It makes it easier to track changes. You might also want to clean up the commit message.

**Comment by exonintrendo** [comment]
I've adjusted the code to accept an `onError` function that is separately called when no ad is retrieved. Attempted to use the same logic you're using when passing down the 'successful' callback into the recursive function calls, but you might want to double check my logic.

**Comment by jonhoo** [comment]
See inline comments. As mentioned above, it would also be great if you could split this into multiple PRs, one for each logical change.

**Comment by exonintrendo** [comment]
Pulling these into their own PRs. Thanks for the help so far!

**Comment by jonhoo** [comment]
Replaced by #13.

**Pull request closed without merging**
