### PR TITLE
Support aborting further VAST queries after unwrapping `X` wrappers.

### PR DESCRIPTION
**Pull request by sterpe**
Tried to avoid changing the existing API.  

A `VASTAd` object now gets a property `abortLimit` which is always -1 of it's `parentAd`, if it has one.  `queryVAST` fn will cancel the next `fetchXML` call when the `parentAd`'s `abortLimit` is zero (`0`) and immediately call the `onError` callback.  The default abort limit is set in `VAST_VMAP_XHROptions.defaultVASTAbortLimit`.   Setting this limit to `-1`, the default, implies that there is no limit, the current behavior.  Don't set to `0` as weirdness may occur.

++ Unit tests covering both cases -- 2 depth wrappers, with the limit set at -1, and 1, respectively.

### CODE REVIEW

**Comment by jonhoo** [comment]
What is the use-case for this?
Also, perhaps disallow setting this to 0?

**Comment by sterpe** [comment]
@jonhoo The use case is that the client doesn't want to just keep following the VASTWrapper chain indefinitely.  Sometime, IRL, we see WrapperChains that are LONG, like 20+ wrappers, and nobody, especially publishers, really wants the user to have to wait for forever before we either have an ad or just abandon the impression and proceed with the content video.

Let me look at what happens if you set the value explicitly at `0`.  I just didn't fully follow that code path.  I'll get back to you on that.

**Comment by sterpe** [comment]
And in VAST4 the iab has sort of retconned the wrapper limit by saying, "that 5 wrappers is a reasonable limit to abandon further vast requests if there is no ad."

**Comment by jonhoo** [comment]
@sterpe: ah, that makes sense. The VAST4 note might be worth adding a reference to.

**Comment by sterpe** [comment]
@jonhoo.  I will add that then.  I also am adding some comments, and have made `0` do what I think we would expect (it actually has the same behavior as `1`)...however I will modify to fetch nothing, not even the first VAST response.  Which is sort of pointless, but at least no surprises...lol.  Push something up in a bit.

**Comment by jonhoo** [comment]
I'm wondering whether it'd be better to disallow 0 as a setting altogether? Say that `0 == -1`, and print a warning in the console. When would 0 ever be a sensible value?

**Comment by sterpe** [comment]
I can throw in that case too, it is sort of pointless to set at 0, you wouldn't fetch anything at all.

**Comment by sterpe** [comment]
Well, okay what's gonna happen is the onError cb will be called with e.toString() === 'Reached abort limit of (0) wrappers.'

Or just throw to the console ?  What do you say?

**Comment by jonhoo** [comment]
Well, `onError` didn't use to have any arguments. I'm fine with adding one though. I think we should only log to console if no `onError` function is given.

**Comment by sterpe** [comment]
Okay, fair enough.  I'll log to the console and if there is an onError I will call that.

**Comment by sterpe** [comment]
Do you prefer actually log, or just throw uncaught exception in a new execution context via setTimeout?

**Comment by jonhoo** [comment]
I think I'd prefer logging unless you have a strong preference otherwise.

```javascript
if ("warn" in console) {
  console.warn(...);
} else {
  console.log(...);
}
```

**Comment by sterpe** [comment]
@jonhoo what's you thought on this?  Sorry I probably should have put together an issue before the PR.  I'll make sure that I do that in the future with anything else we'd like to commit back to you.

**Comment by jonhoo** [comment]
@sterpe: no worries -- I'm happy to discuss this in PRs too. The PR is looking good now, though I'm curious about the line `if (typeof buster === "undefined")`. Why are you doing this?

**Comment by sterpe** [comment]
Yeah, that I did because when running the unit tests, Buster was logging scary warnings there...which don't affect the test but the "warn" is yellow.  I didn't know how we feel about that, so I just silenced it if the buster global is present ( & keep everything green :)).  I saw this was being done here https://github.com/sterpe/vast-vmap/blob/master/src/vast-vmap.js#L241 in the tracker.

**Comment by jonhoo** [comment]
Fair enough. We don't really need the warnings in Buster anyway. Thanks for the PR!

**Pull request merged**
