### PR TITLE
Error callback support

### PR DESCRIPTION
**Pull request by exonintrendo**
Added support for an `onError` callback to be passed into `queryVAST` in addition to the success callback.

### CODE REVIEW

**Comment by exonintrendo** [comment]
I'm not sure if my implementation of the `onReceivedError` counter is correct as you described. Here's what I have, let me know what I missed.

**Comment by exonintrendo** [comment]
Updated, got mixed up with the `onError` vs `onAdError` calls. Been looking at this way too long...

**Comment by jonhoo** [comment]
Almost there :)

First, `onReceivedErrorCounter` has to be a property of `this`, since it's counting the number of fetch failures for *this* vast (and not all the other ones). Second, the check for `onReceivedErrorCounter == adElements.length` has to happen inside `onAdError`. Where it stands now, `onError` will only be called if the vast contains no ads at all (i.e. `adElements.length == 0`).

**Comment by exonintrendo** [comment]
Gotcha. Also, I moved `var that = this` up a bit higher since I'm pretty sure it needs to be referenced in the `onAdError` call.

**Comment by jonhoo** [comment]
Great, it looks pretty good now. It'd also be great if you could include a test case for this. Add a `test/asset` xml file that includes wrappers that include no ads, and in the test code (add a new `test/test-XXX.js`), ensure that `onError` is called exactly once.

**Comment by jonhoo** [comment]
Could you add a test where the wrapper points to another VAST file that is then empty too, just to check that the recursion works?

**Comment by exonintrendo** [comment]
I think that should do it...

**Comment by jonhoo** [comment]
Adopted with [a few modifications](https://github.com/jonhoo/vast-vmap/compare/b3a431cd11c0a4d7cb8b3af2222da9beb62240db...4b31cb4dd6fe8957e476bab8c3982593aacdab45). Thanks!

**Pull request closed without merging**
